targets:
  $default:
    builders:
      builders_for_perception|annotations:
        enabled: true

builders:
  builders_for_perception:
    target: ":builders_for_perception"
    import: "package:builders_for_perception/builders_for_perception.dart"
    builder_factories: ["beliefsBuilderFactory"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
