name: builders_for_perception
description: Builders for generating classes in apps using perception.
publish_to: none
version: 0.0.0-a1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  build: ^2.4.0
  source_gen: ^1.3.2
  analyzer: ^5.13.0

  types_for_perception: ^0.0.0-a1

dev_dependencies:
  test: ^1.24.3
  build_runner: ^2.4.5
  enspyr_lints: ^0.0.0-a1
